name: hot_and_cold
description: A simple Flame game.
version: 0.1.0

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flame: 1.12.0
  flame_audio: 2.1.5
  flame_fire_atlas: 1.4.5
  flame_forge2d: 0.16.0+2
  flame_oxygen: 0.1.9+5
  flame_rive: 1.9.8
  flame_svg: 1.8.7
  flame_tiled: 1.18.1
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: 1.1.2
  flame_test: 1.15.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: false

  assets:
    - assets/platform_tiles/FireTiles/
    - assets/platform_tiles/IceTiles/
    - assets/fire_effects_16_x_16.png
    - assets/fire_1.fa
